name: Python CI/CD for FAIR-SEA

on:
  push:
    branches: [ "main" ]

jobs:
  # Job 1: CI - Test the code for quality
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: pytest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  # Job 2: CD - Deploy the package internally
  deploy:
    name: Deploy to GitHub Packages
    needs: build-and-test # Only runs if the tests above pass
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Permission to publish packages
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish package to GitHub Packages
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          # repository_url: https://pypi.pkg.github.com/${{ github.repository_owner }}